services:
  # ---- NestJS Application ----
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    command: sh -c "npx prisma db push && node dist/src/main.js"
    volumes:
      - ./uploads:/app/uploads #Keeps uploaded images safe on local pc
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=mysql://ProjectBE_ADMIN:ADMIN1234567@mysql:3306/HotelBookingSystem_DB
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=ProjectBE_ADMIN
      - DB_PASSWORD=ADMIN1234567
      - DB_NAME=HotelBookingSystem_DB
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  # ---- mySQL ----
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=RiywSuPasS4252_
      - MYSQL_DATABASE=HotelBookingSystem_DB
      # --- Tell MySQL to actually create the user that API is looking for ---
      - MYSQL_USER=ProjectBE_ADMIN
      - MYSQL_PASSWORD=ADMIN1234567
    ports:
      - "3307:3306" # Expose to host for debugging (optional in prod)
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -pRiywSuPasS4252_" ]      
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s # Give MySQL time for first-time initialization

  # ---- Redis (for caching, queues, sessions) ----
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysqldata:
  redisdata:
